FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

ADD binary_s3_cache /usr/local/bin/s3_cache

ENTRYPOINT ["/usr/local/bin/s3_cache"]
